### PR TITLE
Add bonusly

### PR DESCRIPTION
**Pull request by msyvr**
Hey, sorry for the mess. The final one is all I was wanting to include. Trying to figure out if there's a way to delete the rest to clean this up...

### CODE REVIEW

**Comment by mctaylorpants** [comment]
Thanks for the PR! 😄 Don't worry about the commits, I can squash them down into one when I merge.

Could you add a description of how Bonusly uses Rails? See the other apps for some examples.

**Comment by mctaylorpants** [comment]
Ah, just saw your note about Rails description and version. [According to this job posting](https://angel.co/jobs?slug=bonusly), it looks like they use Rails for their core app with a MonogDB backend. So we could say:

> Bonusly's core application runs on Rails, and uses MongoDB for a datastore (utilizing Mongoid as the ODM).

**Comment by msyvr** [comment]
Thanks for digging that up - I updated the branch. If I need to do anything else, let me know.

**Comment by mctaylorpants** [comment]
Looks great! Thanks for the contribution 🎉

**Pull request merged**
